// svelte-client/src/components/Solo/CPUAnalysisModal.svelte
<script lang="ts">
  import { push } from 'svelte-spa-router'
  import { GAME_CONFIG, DIFFICULTY_CONFIG, calculateCPUPerformanceTime, calculateDynamicCPUInterval, formatTimeString, CPU_PERFORMANCE_DATA, getCPUPerformanceForSets } from '@react-set/common'

  interface CPUAnalysisModalProps {
    currentDifficulty: number
    isOpen: boolean
    onClose: () => void
  }

  let { currentDifficulty, isOpen, onClose }: CPUAnalysisModalProps = $props()
  // svelte-ignore state_referenced_locally
  let selectedDifficulty = $state(currentDifficulty)
  let selectedSetsOnBoard = $state(3)

  // Update selectedDifficulty when currentDifficulty changes
  $effect(() => {
    selectedDifficulty = currentDifficulty
  })

  const performance = $derived(
    calculateCPUPerformanceTime(selectedDifficulty, selectedSetsOnBoard),
  )

  const dynamicInterval = $derived(
    calculateDynamicCPUInterval(selectedDifficulty, selectedSetsOnBoard),
  )

  const dynamicAverageTimeSeconds = $derived(
    Math.round(
      (performance.performanceData.averageAttempts * dynamicInterval) / 1000,
    ),
  )

  function getDifficultyDescription(avgTime: number) {
    if (avgTime <= 10) return { text: 'Very Fast', color: 'danger' }
    if (avgTime <= 20) return { text: 'Fast', color: 'warning' }
    if (avgTime <= 40) return { text: 'Moderate', color: 'info' }
    if (avgTime <= 60) return { text: 'Slow', color: 'secondary' }
    return { text: 'Very Slow', color: 'dark' }
  }
</script>

{#if isOpen}
  <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
  <div class="modal-backdrop" role="button" tabindex="0" onclick={onClose} onkeydown={(e) => e.key === 'Escape' && onClose()}>
    <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
    <div class="modal show d-block" role="dialog" tabindex="-1" onclick={(e) => e.stopPropagation()} onkeydown={(e) => e.key === 'Escape' && onClose()}>
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">CPU Performance Analysis</h5>
            <button type="button" class="btn-close" aria-label="Close" onclick={onClose}></button>
          </div>
          <div class="modal-body">
            <div class="row mb-4">
              <div class="col-md-6">
                <label for="difficultyRange" class="form-label fw-bold">Difficulty Level</label>
                <input
                  id="difficultyRange"
                  type="range"
                  min={DIFFICULTY_CONFIG.min}
                  max={DIFFICULTY_CONFIG.max}
                  step={DIFFICULTY_CONFIG.step}
                  bind:value={selectedDifficulty}
                  class="form-range"
                />
                <div class="text-center">
                  <span class="badge bg-primary">{selectedDifficulty}</span>
                </div>
              </div>
              <div class="col-md-6">
                <label for="setsRange" class="form-label fw-bold">Sets on Board</label>
                <input
                  id="setsRange"
                  type="range"
                  min={1}
                  max={6}
                  step={1}
                  bind:value={selectedSetsOnBoard}
                  class="form-range"
                />
                <div class="text-center">
                  <span class="badge bg-success">
                    {selectedSetsOnBoard} set{selectedSetsOnBoard !== 1 ? 's' : ''}
                  </span>
                </div>
              </div>
            </div>

            <div class="card mb-4">
              <div class="card-header bg-primary text-white">
                <h6 class="mb-0">
                  Analysis: Difficulty {selectedDifficulty} with {selectedSetsOnBoard} set
                  {selectedSetsOnBoard !== 1 ? 's' : ''} on board
                </h6>
              </div>
              <div class="card-body">
                <div class="row text-center">
                  <div class="col-md-3">
                    <div class="border rounded p-2 mb-2">
                      <div class="fw-bold text-primary fs-5">
                        {(dynamicInterval / 1000).toFixed(1)}s
                      </div>
                      <small class="text-muted">Per Attempt</small>
                    </div>
                  </div>
                  <div class="col-md-3">
                    <div class="border rounded p-2 mb-2">
                      <div class="fw-bold text-info fs-5">
                        {performance.averageAttempts.toFixed(1)}
                      </div>
                      <small class="text-muted">Avg Attempts</small>
                    </div>
                  </div>
                  <div class="col-md-3">
                    <div class="border rounded p-2 mb-2">
                      <div class="fw-bold text-success fs-5">
                        {formatTimeString(dynamicAverageTimeSeconds)}
                      </div>
                      <small class="text-muted">Avg Time</small>
                    </div>
                  </div>
                  <div class="col-md-3">
                    <div class="border rounded p-2 mb-2">
                      <div class="fw-bold text-warning fs-5">
                        {formatTimeString(performance.typicalRangeSeconds.fast)}-
                        {formatTimeString(performance.typicalRangeSeconds.slow)}
                      </div>
                      <small class="text-muted">Typical Range</small>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <small class="text-muted me-auto">
              Data based on 1000-trial simulations per scenario
            </small>
            <button type="button" class="btn btn-secondary" onclick={onClose}>
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
{/if}

<style>
  .modal-backdrop {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
    z-index: 1040;
  }

  .modal {
    z-index: 1050;
  }

  .modal-content {
    background-color: #f7f8fa;
    border: 1px solid #e8eaed;
    border-radius: 8px;
  }

  .modal-header {
    border-bottom: 1px solid #e8eaed;
    padding: 1rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .modal-body {
    padding: 1rem;
  }

  .modal-footer {
    border-top: 1px solid #e8eaed;
    padding: 1rem;
    display: flex;
    justify-content: flex-end;
    align-items: center;
  }

  .btn-close {
    background: none;
    border: none;
    font-size: 1.5rem;
    cursor: pointer;
    color: #6c757d;
  }

  .form-range {
    width: 100%;
  }

  .form-label {
    margin-bottom: 0.5rem;
  }

  .card {
    background-color: #f7f8fa;
    border: 1px solid #e8eaed;
    border-radius: 8px;
    margin-bottom: 1rem;
  }

  .card-header {
    padding: 0.75rem 1rem;
    border-bottom: 1px solid #e8eaed;
    border-radius: 8px 8px 0 0;
  }

  .card-body {
    padding: 1rem;
  }

  .bg-primary {
    background-color: #4f46e5 !important;
  }

  .text-white {
    color: white !important;
  }

  .text-primary {
    color: #4f46e5 !important;
  }

  .text-info {
    color: #0891b2 !important;
  }

  .text-success {
    color: #16a34a !important;
  }

  .text-warning {
    color: #d97706 !important;
  }

  .text-muted {
    color: #6c757d !important;
  }

  .fw-bold {
    font-weight: 700 !important;
  }

  .fs-5 {
    font-size: 1.25rem !important;
  }

  .border {
    border: 1px solid #dee2e6 !important;
  }

  .rounded {
    border-radius: 0.375rem !important;
  }

  .p-2 {
    padding: 0.5rem !important;
  }

  .mb-2 {
    margin-bottom: 0.5rem !important;
  }

  .mb-4 {
    margin-bottom: 1.5rem !important;
  }

  .me-auto {
    margin-right: auto !important;
  }
</style>

// vite-client/src/components/Solo/CPUAnalysisModal.tsx
import React, { useState } from 'react'
import {
  calculateCPUPerformanceTime,
  formatTimeString,
  CPU_PERFORMANCE_DATA,
} from './cpuPerformance'
import { DIFFICULTY_CONFIG } from './constants'

interface CPUAnalysisModalProps {
  currentDifficulty: number
  isOpen: boolean
  onClose: () => void
}

const CPUAnalysisModal: React.FC<CPUAnalysisModalProps> = ({
  currentDifficulty,
  isOpen,
  onClose,
}) => {
  const [selectedDifficulty, setSelectedDifficulty] = useState(currentDifficulty)
  const [selectedSetsOnBoard, setSelectedSetsOnBoard] = useState(3)

  if (!isOpen) return null

  const performance = calculateCPUPerformanceTime(selectedDifficulty, selectedSetsOnBoard)
  const {
    cpuTurnInterval,
    averageAttempts,
    medianAttempts,
    averageTimeSeconds,
    medianTimeSeconds,
    typicalRangeSeconds,
    performanceData,
  } = performance

  return (
    <div className="modal fade show d-block" style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}>
      <div className="modal-dialog modal-lg">
        <div className="modal-content">
          <div className="modal-header">
            <h5 className="modal-title">
              <i className="bi bi-cpu me-2"></i>
              CPU Performance Analysis
            </h5>
            <button type="button" className="btn-close" onClick={onClose}></button>
          </div>

          <div className="modal-body">
            {/* Controls */}
            <div className="row mb-4">
              <div className="col-md-6">
                <label className="form-label fw-bold">Difficulty Level</label>
                <input
                  type="range"
                  min={DIFFICULTY_CONFIG.min}
                  max={DIFFICULTY_CONFIG.max}
                  step={DIFFICULTY_CONFIG.step}
                  value={selectedDifficulty}
                  onChange={(e) => setSelectedDifficulty(Number(e.target.value))}
                  className="form-range"
                />
                <div className="text-center">
                  <span className="badge bg-primary">{selectedDifficulty}</span>
                </div>
              </div>

              <div className="col-md-6">
                <label className="form-label fw-bold">Sets on Board</label>
                <input
                  type="range"
                  min={1}
                  max={6}
                  step={1}
                  value={selectedSetsOnBoard}
                  onChange={(e) => setSelectedSetsOnBoard(Number(e.target.value))}
                  className="form-range"
                />
                <div className="text-center">
                  <span className="badge bg-success">
                    {selectedSetsOnBoard} set{selectedSetsOnBoard !== 1 ? 's' : ''}
                  </span>
                </div>
              </div>
            </div>

            {/* Current Analysis */}
            <div className="card mb-4">
              <div className="card-header bg-primary text-white">
                <h6 className="mb-0">
                  Analysis: Difficulty {selectedDifficulty} with {selectedSetsOnBoard} set
                  {selectedSetsOnBoard !== 1 ? 's' : ''} on board
                </h6>
              </div>
              <div className="card-body">
                <div className="row text-center">
                  <div className="col-md-3">
                    <div className="border rounded p-2 mb-2">
                      <div className="fw-bold text-primary fs-5">
                        {(cpuTurnInterval / 1000).toFixed(1)}s
                      </div>
                      <small className="text-muted">Per Attempt</small>
                    </div>
                  </div>

                  <div className="col-md-3">
                    <div className="border rounded p-2 mb-2">
                      <div className="fw-bold text-info fs-5">{averageAttempts.toFixed(1)}</div>
                      <small className="text-muted">Avg Attempts</small>
                    </div>
                  </div>

                  <div className="col-md-3">
                    <div className="border rounded p-2 mb-2">
                      <div className="fw-bold text-success fs-5">
                        {formatTimeString(averageTimeSeconds)}
                      </div>
                      <small className="text-muted">Avg Time</small>
                    </div>
                  </div>

                  <div className="col-md-3">
                    <div className="border rounded p-2 mb-2">
                      <div className="fw-bold text-warning fs-5">
                        {formatTimeString(typicalRangeSeconds.fast)}-
                        {formatTimeString(typicalRangeSeconds.slow)}
                      </div>
                      <small className="text-muted">Typical Range</small>
                    </div>
                  </div>
                </div>

                <div className="mt-3 p-2 bg-light rounded">
                  <small className="text-muted">
                    <strong>Interpretation:</strong> At difficulty {selectedDifficulty}, the CPU
                    attempts to find a set every {(cpuTurnInterval / 1000).toFixed(1)} seconds.
                    With {selectedSetsOnBoard} set{selectedSetsOnBoard !== 1 ? 's' : ''} available,
                    it takes an average of {averageAttempts.toFixed(1)} attempts (
                    {formatTimeString(averageTimeSeconds)} total) to successfully find one.
                  </small>
                </div>
              </div>
            </div>

            {/* Performance Matrix */}
            <PerformanceMatrix selectedDifficulty={selectedDifficulty} />

            {/* Detailed Statistics */}
            <DetailedStatistics performanceData={performanceData} />
          </div>

          <div className="modal-footer">
            <small className="text-muted me-auto">
              Data based on 1000-trial simulations per scenario
            </small>
            <button type="button" className="btn btn-secondary" onClick={onClose}>
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

const PerformanceMatrix: React.FC<{ selectedDifficulty: number }> = ({ selectedDifficulty }) => {
  return (
    <div className="card mb-4">
      <div className="card-header">
        <h6 className="mb-0">
          Performance Matrix: Difficulty {selectedDifficulty} vs Sets on Board
        </h6>
      </div>
      <div className="card-body">
        <div className="table-responsive">
          <table className="table table-sm table-hover">
            <thead className="table-light">
              <tr>
                <th>Sets on Board</th>
                <th>Avg Attempts</th>
                <th>Time per Attempt</th>
                <th>Total Avg Time</th>
                <th>Typical Range</th>
              </tr>
            </thead>
            <tbody>
              {CPU_PERFORMANCE_DATA.map((data) => {
                const perf = calculateCPUPerformanceTime(selectedDifficulty, data.setsOnBoard)
                return (
                  <tr key={data.setsOnBoard}>
                    <td>
                      <span className="badge bg-secondary">{data.setsOnBoard}</span>
                    </td>
                    <td>{perf.averageAttempts.toFixed(1)}</td>
                    <td>{(perf.cpuTurnInterval / 1000).toFixed(1)}s</td>
                    <td>
                      <span className="fw-bold text-primary">
                        {formatTimeString(perf.averageTimeSeconds)}
                      </span>
                    </td>
                    <td>
                      <small className="text-muted">
                        {formatTimeString(perf.typicalRangeSeconds.fast)} -{' '}
                        {formatTimeString(perf.typicalRangeSeconds.slow)}
                      </small>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}

const DetailedStatistics: React.FC<{ performanceData: any }> = ({ performanceData }) => {
  return (
    <div className="card">
      <div className="card-header">
        <h6 className="mb-0">Detailed Statistics</h6>
      </div>
      <div className="card-body">
        <div className="row">
          <div className="col-md-6">
            <h6 className="text-muted">Attempt Distribution</h6>
            <ul className="list-unstyled">
              <li>
                <strong>Average:</strong> {performanceData.averageAttempts.toFixed(1)} attempts
              </li>
              <li>
                <strong>Median:</strong> {performanceData.medianAttempts} attempts
              </li>
              <li>
                <strong>25th percentile:</strong> {performanceData.percentiles.p25} attempts
              </li>
              <li>
                <strong>75th percentile:</strong> {performanceData.percentiles.p75} attempts
              </li>
              <li>
                <strong>90th percentile:</strong> {performanceData.percentiles.p90} attempts
              </li>
            </ul>
          </div>

          <div className="col-md-6">
            <h6 className="text-muted">Performance Insights</h6>
            <ul className="list-unstyled">
              <li>
                <strong>Best case:</strong> {performanceData.range.min} attempt
                {performanceData.range.min !== 1 ? 's' : ''}
              </li>
              <li>
                <strong>Worst case:</strong> {performanceData.range.max} attempts
              </li>
              <li>
                <strong>Success rate:</strong> 100% (CPU always finds available sets)
              </li>
              <li>
                <strong>Strategy:</strong> Random 2-card selection
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-3 p-3 bg-info bg-opacity-10 rounded">
          <h6 className="text-info">How CPU Strategy Works</h6>
          <small className="text-muted">
            The CPU randomly selects 2 cards from the board, calculates what the 3rd card would
            need to be to complete a set, then checks if that card exists on the board. If yes, it
            finds the set. If no, it tries again with 2 different cards. This process repeats until
            a set is found.
          </small>
        </div>
      </div>
    </div>
  )
}

export default CPUAnalysisModal
