// svelte-client/src/components/Board.svelte
<script lang="ts">
  import Card from './Card.svelte'
  import TopBar from './TopBar.svelte'

  interface PlayerInfo {
    name: string
    score: number
    color: string
  }

  interface BoardProps {
    board: string[]
    selected: string[]
    setFound: boolean
    gameOver: boolean
    score: number
    elapsedTime?: number
    timeLeft?: number
    declarer?: string | null
    gameMode?: 'training' | 'versus'
    players?: Record<string, PlayerInfo>
    onCardClick: (card: string) => void
  }

  let { board, selected, setFound, gameOver, score, elapsedTime, timeLeft, declarer = null, gameMode = 'training', players = {}, onCardClick }: BoardProps =
    $props()

  const borderColor = '#4fc3f7'

  function isSelected(card: string): boolean {
    return selected.includes(card)
  }

  function shouldBlur(card: string): boolean {
    return setFound && selected.length === 3 && !selected.includes(card)
  }
</script>

<TopBar {gameMode} {board} {declarer} {elapsedTime} {score} {timeLeft} />

<div class="container bg-light-purple">
  <div class="board d-flex flex-column align-items-center">
    <div class="board-main-container">
      {#each board as card, index (card + '-' + index)}
        <div class="card-wrapper" role="button" tabindex="0" onclick={() => onCardClick(card)} onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') onCardClick(card) }}>
          <div
            class="card-holder"
            style={isSelected(card) ? `background-color: ${borderColor}` : ''}
          >
            <div class="card {shouldBlur(card) ? 'blurry' : ''}">
              <Card desc={card} />
            </div>
          </div>
        </div>
      {/each}
    </div>

    {#if gameMode === 'versus' && Object.keys(players).length > 0}
      <div class="row my-1 text-center fixed-bottom">
        {#each Object.entries(players) as [name, info]}
          <div class="col s4 m3">
            <span
              class="player-name"
              style="background-color: {info.color}; color: white; border-radius: 4px;"
            >
              {name}: {info.score}
            </span>
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>

<style>
  .board {
    margin-top: 60px;
  }

  .board-main-container {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-row-gap: 75px;
    column-gap: 0px;
    margin-bottom: 20px;
  }

  .card-holder {
    margin: 1px;
    padding: 3px;
    border-radius: 3px;
  }

  .card-wrapper {
    cursor: pointer;
  }

  .player-name {
    padding: 3px 8px;
  }

  .fixed-bottom {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 100;
    padding: 8px 0;
    background-color: #e4deff;
  }

  .row {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 12px;
  }

  .blurry {
    filter: grayscale(0.9) blur(7px);
  }

  @media screen and (min-width: 560px) {
    .board {
      margin-top: 20px;
    }

    .card-holder {
      margin: 4px;
      padding: 4px;
      border-radius: 4px;
    }

    .board-main-container {
      grid-template-columns: repeat(3, 1fr);
      row-gap: 20px;
      column-gap: 20px;
    }
  }

  @media screen and (max-width: 560px) {
    :global(html),
    :global(#app),
    .container {
      background-color: #f7f8fa;
    }

    .card-wrapper {
      transform: rotate(90deg) scale(1.15);
    }
  }
</style>

// preact-client/src/components/Board.tsx
import { useMemo } from 'preact/hooks'
import { countSets } from '@/utils/helpers'
import { Card } from './Card'

interface PlayerInfo {
  name: string
  score: number
  color: string
}

interface BoardProps {
  board: string[]
  selected: string[]
  setFound: boolean
  gameOver: boolean
  score: number
  elapsedTime?: number
  timeLeft?: number
  declarer?: string | null
  gameMode?: 'training' | 'versus'
  players?: Record<string, PlayerInfo>
  onCardClick: (card: string) => void
}

export function Board({
  board,
  selected,
  setFound,
  gameOver,
  score,
  elapsedTime = 0,
  timeLeft = 0,
  declarer = null,
  gameMode = 'training',
  players = {},
  onCardClick,
}: BoardProps) {
  // Only recompute when the board itself changes — not on every elapsed-time
  // tick, which re-renders Board each second with the same board reference.
  const setsOnBoard = useMemo(
    () => countSets(board, { debug: import.meta.env.DEV } as any),
    [board],
  )

  function formatTime(seconds: number): string {
    const mm = Math.floor(seconds / 60)
    const ss = seconds % 60
    return `${mm}:${String(ss).padStart(2, '0')}`
  }

  // Highlight selected cards in the declarer's color (e.g. the CPU's color when
  // the CPU is picking), falling back to a neutral blue when nobody's declared.
  const borderColor = (declarer && players[declarer]?.color) || '#4fc3f7'

  function isSelected(card: string): boolean {
    return selected.includes(card)
  }

  function shouldBlur(card: string): boolean {
    return setFound && selected.length === 3 && !selected.includes(card)
  }

  return (
    <>
      {gameMode === 'versus' ? (
        <div class="topbar py-2 bg-dark-orange">
          <nav class="text-white">
            <div class="d-flex justify-content-around text-center">
              <div>
                Sets: <span class="mono-font">{setsOnBoard}</span>
              </div>
              <div>
                Time: <span class="mono-font">{formatTime(elapsedTime)}</span>
              </div>
              <div>{declarer ? `SET! ${declarer}` : ''}</div>
            </div>
          </nav>
        </div>
      ) : (
        <div class="topbar py-2 bg-dark-orange">
          <nav>
            <div class="nav-wrapper d-flex justify-content-around">
              <div>
                Time: <span class="mono-font">{formatTime(elapsedTime)}</span>
              </div>
              <div>
                Score: <span class="mono-font">{score}</span>
              </div>
              <div>
                Remaining:{' '}
                <span class="mono-font">{timeLeft > 0 ? timeLeft.toFixed(1) : '0.0'}</span>
              </div>
            </div>
          </nav>
        </div>
      )}

      <div class="container bg-light-purple">
        <div class="board d-flex flex-column align-items-center">
          <div class="board-main-container">
            {board.map((card) => (
              <div
                key={card}
                class="card-wrapper"
                role="button"
                tabindex={0}
                onClick={() => onCardClick(card)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') onCardClick(card)
                }}
              >
                <div
                  class="card-holder"
                  style={isSelected(card) ? `background-color: ${borderColor}` : ''}
                >
                  <div class={`card ${shouldBlur(card) ? 'blurry' : ''}`}>
                    <Card desc={card} />
                  </div>
                </div>
              </div>
            ))}
          </div>

          {gameMode === 'versus' && Object.keys(players).length > 0 && (
            <div class="row my-1 text-center fixed-bottom">
              {Object.entries(players).map(([name, info]) => (
                <div key={name} class="col s4 m3">
                  <span
                    class="player-name"
                    style={`background-color: ${info.color}; color: white; border-radius: 4px;`}
                  >
                    {name}: {info.score}
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </>
  )
}
