// svelte-client/src/components/Board.svelte
<script lang="ts">
  import Card from './Card.svelte'
  import TopBar from './TopBar.svelte'

  interface PlayerInfo {
    name: string
    score: number
    color: string
  }

  interface BoardProps {
    board: string[]
    selected: string[]
    setFound: boolean
    gameOver: boolean
    score: number
    elapsedTime?: number
    timeLeft?: number
    declarer?: string | null
    gameMode?: 'training' | 'versus'
    players?: Record<string, PlayerInfo>
    onCardClick: (card: string) => void
  }

  let { board, selected, setFound, gameOver, score, elapsedTime, timeLeft, declarer = null, gameMode = 'training', players = {}, onCardClick }: BoardProps =
    $props()

  const borderColor = '#4fc3f7'

  function isSelected(card: string): boolean {
    return selected.includes(card)
  }

  function shouldBlur(card: string): boolean {
    return setFound && selected.length === 3 && !selected.includes(card)
  }
</script>

<TopBar {gameMode} {board} {declarer} {elapsedTime} {score} {timeLeft} />

<div class="container bg-light-purple">
  <div class="board d-flex flex-column align-items-center">
    <div class="board-main-container">
      {#each board as card, index (card + '-' + index)}
        <div class="card-wrapper" role="button" tabindex="0" onclick={() => onCardClick(card)} onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') onCardClick(card) }}>
          <div
            class="card-holder"
            style={isSelected(card) ? `background-color: ${borderColor}` : ''}
          >
            <div class="card {shouldBlur(card) ? 'blurry' : ''}">
              <Card desc={card} />
            </div>
          </div>
        </div>
      {/each}
    </div>

    {#if gameMode === 'versus' && Object.keys(players).length > 0}
      <div class="row my-1 text-center fixed-bottom">
        {#each Object.entries(players) as [name, info]}
          <div class="col s4 m3">
            <span
              class="player-name"
              style="background-color: {info.color}; color: white; border-radius: 4px;"
            >
              {name}: {info.score}
            </span>
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>

<style>
  .board {
    margin-top: 60px;
  }

  .board-main-container {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-row-gap: 75px;
    column-gap: 0px;
    margin-bottom: 20px;
  }

  .card-holder {
    margin: 1px;
    padding: 3px;
    border-radius: 3px;
  }

  .card-wrapper {
    cursor: pointer;
  }

  .player-name {
    padding: 3px 8px;
  }

  .fixed-bottom {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 100;
    padding: 8px 0;
    background-color: #e4deff;
  }

  .row {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 12px;
  }

  .blurry {
    filter: grayscale(0.9) blur(7px);
  }

  @media screen and (min-width: 560px) {
    .board {
      margin-top: 20px;
    }

    .card-holder {
      margin: 4px;
      padding: 4px;
      border-radius: 4px;
    }

    .board-main-container {
      grid-template-columns: repeat(3, 1fr);
      row-gap: 20px;
      column-gap: 20px;
    }
  }

  @media screen and (max-width: 560px) {
    :global(html),
    :global(#app),
    .container {
      background-color: #f7f8fa;
    }

    .card-wrapper {
      transform: rotate(90deg) scale(1.15);
    }
  }
</style>

// vite-client/src/components/Board.tsx
import React, { Fragment, useEffect, useState } from 'react'
import { debounce, get, isEmpty, map } from 'lodash'

import Card from './Card'
import GameOver from './GameOver'
import { Modal } from 'react-bootstrap'
import TopBar from './TopBar'
import { countSets } from '../utils/helpers'
import SharedPlayersDisplay from './SharedPlayersDisplay'
import { Players } from '../utils/models' // Import Players interface

interface BoardProps {
  board: string[]
  deck: string[]
  selected: string[]
  declarer: string | null
  handleCardClick: (card: string) => void
  handleDeclare: () => void
  handleRedeal?: () => void
  players: Players // Use Players interface
  setFound: boolean
  gameOver: string | null | boolean
  myName: string
  resetGame: () => void
  solo: boolean
  gameMode: string
  elapsedTime?: number
  timeLeft?: number | string
}

function Board(props: BoardProps) {
  const [sets, setSets] = useState<number | null>(null)
  const [windowHeight, setWindowHeight] = useState(window.innerHeight)
  const { board, selected, deck, declarer, players, gameOver, myName, setFound, solo, gameMode } =
    props

  // Determine if sharedDevice is true based on gameMode
  const sharedDevice = gameMode === 'shared-device'

  useEffect(() => {
    const resize = debounce(() => {
      setWindowHeight(window.innerHeight)
    }, 150)

    window.addEventListener('resize', resize)

    return function cleanup() {
      window.removeEventListener('resize', resize)
    }
  }, [])

  useEffect(() => {
    setSets(countSets(board, { debug: process.env.NODE_ENV !== 'production' }))
  }, [board])

  const getBorderColor = ({
    declarer,
    players,
  }: {
    declarer: string | null
    players: Players
  }) => {
    if (declarer) {
      return get(players, `${declarer}.color`, '')
    }
    return get(players, `${myName}.color`, '')
  }

  const borderColor = getBorderColor(props)

  if (!isEmpty(gameOver)) {
    return <GameOver gameOver={gameOver} myName={myName} solo={solo} reset={props.resetGame} />
  }

  const playersArray = map(players, (info, name) => {
    return {
      name,
      ...info,
    }
  })

  const topBoxes = Math.ceil(playersArray.length / 2)
  const topPlayers = playersArray.slice(0, topBoxes)
  const bottomPlayers = playersArray.slice(topBoxes)

  return (
    <Fragment>
      {(isEmpty(players) || !Object.keys(players).includes(myName)) && (
        <Modal show>
          <Modal.Header>
            <Modal.Title>Waiting to join...</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <h4>Players:</h4>
            <ul className="collection">
              {map(players, (info, name) => {
                return (
                  <li key={name} className="collection-item">
                    <span className={`player-name`}>
                      {name} {info.host && '(host)'}
                    </span>
                  </li>
                )
              })}
            </ul>
          </Modal.Body>
        </Modal>
      )}

      <TopBar {...props} />
      <div className="container bg-light-purple">
        {sharedDevice && (
          <SharedPlayersDisplay
            players={topPlayers}
            declarer={declarer}
            handlePlayerClick={props.handleCardClick} // This was handlePlayerClick in original
          />
        )}

        <div className="board d-flex flex-column align-items-center">
          <div className="board-main-container">
            {board.map((card, index) => {
              const isSelected = selected.includes(card)
              const cardHolderStyle = isSelected ? { backgroundColor: borderColor } : {}
              return (
                <div
                  key={`${card}-${index}`}
                  className={`card-wrapper`}
                  onClick={() => {
                    props.handleCardClick(card)
                  }}
                >
                  <div className="card-holder" style={cardHolderStyle}>
                    <div
                      className={`card ${
                        setFound && selected.length === 3 && !selected.includes(card)
                          ? 'blurry'
                          : ''
                      }`}
                    >
                      <Card desc={card} />
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
          {!sharedDevice && !['puzzle', 'training'].includes(gameMode) && (
            <div className="row my-1 text-center fixed-bottom">
              {map(players, (info, name) => {
                return (
                  <div key={name} className="col s4 m3">
                    <span className={`player-name bg-${info.color}`}>
                      {name}: {info.score}
                    </span>
                  </div>
                )
              })}
            </div>
          )}

          {props.handleRedeal && (
            <div className="row mt-3">
              <div className="col mt-3 mt-md-4">
                <button onClick={props.handleRedeal} className="btn btn-primary">
                  Shuffle
                </button>
              </div>
            </div>
          )}
        </div>
        {sharedDevice && (
          <SharedPlayersDisplay
            players={bottomPlayers}
            declarer={declarer}
            handlePlayerClick={props.handleCardClick} // This was handlePlayerClick in original
          />
        )}
      </div>
    </Fragment>
  )
}

export default Board
