// svelte-client/src/components/Card.svelte
<script lang="ts">
  import { range } from '@/utils/helpers'

  const CARD_COLORS: Record<string, string> = {
    0: '#61d020',
    1: '#1b2f92',
    2: '#ff0000',
    white: '#fafafa',
  }

  const config = {
    width: 120,
    height: 200,
    strokeWidth: 4,
    padding: 25,
  }

  let { desc }: { desc: string } = $props()

  function getFill(color: string, fill: string): string {
    if (fill === '1') {
      return `url(#card-${color}-${fill})`
    }
    if (fill === '2') {
      return CARD_COLORS[color]
    }
    return CARD_COLORS.white
  }

  function getSquigglePath(): string {
    return `
    m-17.49,66
    c50.83,-35.45 101.7,35.45
    152.5,0
    c30,-10 30,43.8
    0,63.8
    c-50.8,35.45 -101.6,-35.45
    -152.5,0
    c-30,15 -30,-45
    0,-63.59
    z
    `
  }
</script>

{#if desc === '0333'}
  <div class="game-card d-flex justify-content-center">
    <svg
      class="shape blank-card"
      viewBox="0 0 {config.width} {config.height}"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect
        x="2"
        y="2"
        width={config.width - 4}
        height={config.height - 4}
        fill="#f8f9fa"
        stroke="#dee2e6"
        stroke-width="2"
        stroke-dasharray="5,5"
        rx="8"
      />
    </svg>
  </div>
{:else}
  {@const [number, color, shape, fill] = desc.split('')}
  {@const fillColor = getFill(color, fill)}
  {@const strokeColor = CARD_COLORS[color]}
  {@const { padding, height, width, strokeWidth } = config}

  <div class="game-card d-flex justify-content-center">
    <svg width="0" height="0">
      <pattern
        id="card-{color}-{fill}"
        width={120 / 12}
        height="10"
        patternTransform="rotate(45 0 0)"
        patternUnits="userSpaceOnUse"
      >
        <line x1="0" y1="0" x2="0" y2="10" style="stroke: {strokeColor}; stroke-width: {strokeWidth}" />
      </pattern>
    </svg>

    {#each range(Number(number) + 1) as _i}
      <svg
        class="shape {number === '1' ? 'double' : ''}"
        viewBox="0 0 {config.width} {config.height}"
        xmlns="http://www.w3.org/2000/svg"
      >
        {#if shape === '0'}
          <!-- Squiggle -->
          <g>
            <path
              stroke={strokeColor}
              transform="rotate(270,58.8,98) scale(0.8 1) translate(10 0)"
              d={getSquigglePath()}
              stroke-width={strokeWidth}
              fill={fillColor}
            />
          </g>
        {:else if shape === '1'}
          <!-- Oval -->
          <ellipse
            stroke={strokeColor}
            ry={(height - 2 * padding) / 2}
            rx={(width - 2 * padding) / 2}
            cy={height / 2}
            cx={width / 2}
            stroke-width={config.strokeWidth}
            fill={fillColor}
          />
        {:else if shape === '2'}
          <!-- Diamond -->
          <polygon
            points="{padding},{height / 2} {width / 2},{padding} {width - padding},{height / 2} {width / 2},{height - padding}"
            style="fill: {fillColor}; stroke: {strokeColor}; stroke-width: {config.strokeWidth}"
          />
        {/if}
      </svg>
    {/each}
  </div>
{/if}

<style>
  .game-card {
    display: flex;
    justify-content: center;
  }

  .shape {
    width: 32%;
    margin: auto;
  }

  .shape.double {
    margin: 0 3px;
  }
</style>

// vite-client/src/components/Card.tsx
import './card.scss'

import React, { Fragment } from 'react'

import { range } from '../utils/helpers'

const config = {
  width: 120,
  height: 200,
  strokeWidth: 4,
  padding: 25,
}

interface RectangleProps {
  fill: string
  color: string
}

const Rectangle: React.FC<RectangleProps> = ({ fill, color }) => {
  const { padding, height, width, strokeWidth } = config
  return (
    <g>
      <polygon
        points={`${padding},${padding}
    ${width - padding},${padding}
    ${width - padding},${height - padding}
    ${padding},${height - padding}`}
        style={{ fill: fill, stroke: color, strokeWidth: strokeWidth }}
      />
    </g>
  )
}

interface SquiggleProps {
  fill: string
  color: string
}

const Squiggle: React.FC<SquiggleProps> = ({ fill, color }) => {
  const { padding, height, width, strokeWidth } = config
  return (
    <svg width="120" height="200" xmlns="http://www.w3.org/2000/svg">
      <g>
        <rect fill="#fff" id="canvas_background" height="202" width="122" y="-1" x="-1" />
        <g
          display="none"
          overflow="visible"
          y="0"
          x="0"
          height="100%"
          width="100%"
          id="canvasGrid"
        >
          <rect fill="#fff" strokeWidth="0" y="0" x="0" height="100%" width="100%" />
        </g>
      </g>
      <g>
        <path
          stroke={color}
          transform="
          rotate(270,58.8,98)
          scale(0.8 1)
          translate(10 0)
          "
          id="svg_5"
          d="
          m-17.49,66
          c50.83,-35.45 101.7,35.45
          152.5,0
          c30,-10 30,43.8
          0,63.8
          c-50.8,35.45 -101.6,-35.45
          -152.5,0
          c-30,15 -30,-45
          0,-63.59
          z
          "
          fillOpacity="null"
          strokeOpacity="null"
          strokeWidth={strokeWidth}
          fill={fill}
        />
      </g>
    </svg>
  )
}

interface ShapeProps {
  shape: string
  fill: string
  color: string
  num: string
}

const Shape: React.FC<ShapeProps> = ({ shape, fill, color, num }) => {
  let { padding, height, width, strokeWidth } = config
  if (shape === '0') {
    padding = padding + 1
    return <Squiggle fill={fill} color={color} />
  }
  if (shape === '1') {
    return (
      <g>
        <ellipse
          stroke={color}
          ry={(height - 2 * padding) / 2}
          rx={(width - 2 * padding) / 2}
          cy={height / 2}
          cx={width / 2}
          fillOpacity="null"
          strokeOpacity="null"
          strokeWidth={config.strokeWidth}
          fill={fill}
        />
      </g>
    )
  }
  if (shape === '2') {
    return (
      <g>
        <polygon
          points={`${padding},${height / 2}
          ${width / 2},${padding}
          ${width - padding},${height / 2}
          ${width / 2},${height - padding}`}
          style={{ fill: fill, stroke: color, strokeWidth: config.strokeWidth }}
        />
      </g>
    )
  }
  return null
}

interface CardProps {
  desc: string
}

const Card: React.FC<CardProps> = ({ desc }) => {
  // Handle blank cards specially
  if (desc === '0333') {
    return (
      <div className="game-card d-flex justify-content-center">
        <svg
          className="shape blank-card"
          viewBox={`0 0 ${config.width} ${config.height}`}
          xmlns="http://www.w3.org/2000/svg"
        >
          <rect
            x="2"
            y="2"
            width={config.width - 4}
            height={config.height - 4}
            fill="#f8f9fa"
            stroke="#dee2e6"
            strokeWidth="2"
            strokeDasharray="5,5"
            rx="8"
          />
        </svg>
      </div>
    )
  }

  const colors: { [key: string]: string } = {
    0: '#61d020',
    1: '#1b2f92',
    2: '#FF0000',
    white: '#fff',
  }

  const getFill = (color: string, fill: string): string => {
    if (fill === '1') {
      return `url(#card-${color}-${fill})`
    }
    if (fill === '2') {
      return colors[color]
    }
    return colors.white
  }

  const drawShape = () => {
    const [num, color, shape, fill] = desc.split('')
    return (
      <Fragment>
        <g>
          <title>background</title>
          <rect fill={colors.white} id="canvas_background" y="-1" x="-1" />
          <g
            display="none"
            overflow="visible"
            y="0"
            x="0"
            height="100%"
            width="100%"
            id="canvasGrid"
          >
            <rect strokeWidth="0" y="0" x="0" height="100%" width="100%" />
          </g>
        </g>
        <Shape shape={shape} num={num} fill={getFill(color, fill)} color={colors[color]} />
      </Fragment>
    )
  }

  const [number, color, , fill] = desc.split('')
  return (
    <div className="game-card d-flex justify-content-center">
      <svg width="0" height="0">
        <pattern
          id={`card-${color}-${fill}`}
          width={120 / 12}
          height="10"
          patternTransform="rotate(45 0 0)"
          patternUnits="userSpaceOnUse"
        >
          <line x1="0" y1="0" x2="0" y2="10" style={{ stroke: colors[color], strokeWidth: '5' }} />
        </pattern>
      </svg>

      {range(Number(number) + 1).map((i) => {
        return (
          <svg
            key={i}
            className={`shape ${number === '1' ? 'double' : ''}`}
            viewBox={`0 0 ${config.width} ${config.height}`}
            xmlns="http://www.w3.org/2000/svg"
          >
            {drawShape()}
          </svg>
        )
      })}
    </div>
  )
}

export default Card
